export default {
  ROUTE_SSMISSD04: 'SSMISSD04',
  SQL_SELECT: 'SSMISSD07.SSMISSD07.select',
  TABLE_INSERT: 't_shukkairaiperson_is',
  PROPSNAMEINSERT: 'SSMISSD07_INSERT',
  PROPSNAMEUPDATE: 'SSMISSD07_UPDATE',
  PROPSNAMEUPDATEFORDEL: 'SSMISSD07_UPDATEFORDEL',
  COLUMN_CHECK_UNIQ: 't_shukkairaiperson_is_seqno',
  COLUMN_EXCLCNT: 'n_excl_cnt',
};
