export default {
  ROUTE_SSMISSD04: 'SSMISSD04',
  SQL_SELECT: 'SSMISSD05.t_shukkairaipack_is.select',
  TABLE_INSERT: 't_shukkairaipack_is',
  PROPSNAMEINSERT: 'SSMISSD05_INSERT',
  PROPSNAMEUPDATE: 'SSMISSD05_UPDATE',
  PROPSNAMEUPDATEFORDEL: 'SSMISSD05_UPDATEFORDEL',
  COLUMN_EXCLCNT: 'n_excl_cnt',
};