export default {
  SQL_SELECT_IRAIPERSONDEFAULT: 'SSMISSD09.m_iraipersondefault_is.select',
  PROPSNAMEINSERT: 'SSMISSD09_INSERT',
  PROPSNAMEUPDATE: 'SSMISSD09_UPDATE',
  APIERROR_MSG_UNNESS: 'empty',
  INIT_IRAI_JP: 'JP',
  INIT_IRAITEL_JP: '+81',
};
