export default {
  FORWARD: 'SSMISRD02',
  COMPLETE: 'SSMISRD05',
  ERROR: 'SSMISRD04',

  STEP1_TITLE: 'お客様情報入力',
  STEP2_TITLE: '入力内容確認',
  STEP3_TITLE: '登録完了',

  MOUSHIKOMI_PANEL_TITTLE: 'お客様コード・申込ID',
  OKYAKUINFO_PANEL_TITTLE: 'スマートクラブお客様情報',

  HAISOKOKYAKU_CD_CAPTION: 'お客様コード',
  MOSHIKOMI_ID_CAPTION: '申込ID',
  USERNO_CAPTION: 'スマートクラブID',
  CUSTOMER_NM_CAPTION: '会社名',
  CUSTOMER_NMK_CAPTION: '会社名カナ',
  BUSHO_NM_CAPTION: '部署名',
  KOKYAKU_NM_CAPTION: 'お名前',
  KOKYAKU_NMK_CAPTION: 'お名前カナ',
  CUSTOMER_TEL_CAPTION: '電話番号',
  CUSTOMER_FAX_CAPTION: '電話番号(FAX)',
  CUSTOMER_MAIL_CAPTION: 'メールアドレス',
  CUSTOMER_YUBIN_CAPTION: '郵便番号',
  CUSTOMER1_ADD_CAPTION: '住所１',
  CUSTOMER2_ADD_CAPTION: '住所２',
  CUSTOMER3_ADD_CAPTION: '住所３',

  ONCLICKBACK_BUTTON_CAPTION: '戻る',
  ONCLICKREGIST_BUTTON_CAPTION: '登録',
};
